### ISSUE TITLE
打不开

### ISSUE THREAD

**Issue by maliaoshui** [madneal/subway-shanghai#27]
该网页已经毁灭。

**Comment by madneal** [comment]
@maliaoshui 因为我修改了用户名， https://madneal.github.io/subway-shanghai

**Comment by jannylz** [comment]
之前的pwa版本为啥不用了，我正在学习pwa想要学习一下

**Comment by madneal** [comment]
> 之前的pwa版本为啥不用了，我正在学习pwa想要学习一下

可以正常使用，没有什么问题
